/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GGroupIdRouteImport } from './routes/g.$groupId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAvatarUserIdRouteImport } from './routes/api/avatar.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupIdRoute = GGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarUserIdRoute = ApiAvatarUserIdRouteImport.update({
  id: '/api/avatar/$userId',
  path: '/api/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/g/$groupId'
    | '/join/$code'
    | '/api/auth/$'
    | '/api/avatar/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/g/$groupId'
    | '/join/$code'
    | '/api/auth/$'
    | '/api/avatar/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/g/$groupId'
    | '/join/$code'
    | '/api/auth/$'
    | '/api/avatar/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  GGroupIdRoute: typeof GGroupIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarUserIdRoute: typeof ApiAvatarUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupId': {
      id: '/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/g/$groupId'
      preLoaderRoute: typeof GGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$userId': {
      id: '/api/avatar/$userId'
      path: '/api/avatar/$userId'
      fullPath: '/api/avatar/$userId'
      preLoaderRoute: typeof ApiAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  GGroupIdRoute: GGroupIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarUserIdRoute: ApiAvatarUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
